version: 2

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true
